version: 2
jobs:
  build:
    machine: true
    steps:
     - run: |
        echo 'export IMAGE_TAG=$(git rev-parse HEAD | head -c 7)' >> $BASH_ENV
        echo 'export PR_NUM=$(echo $CIRCLE_PULL_REQUEST | rev | cut -d/ -f1 | rev)' >> $BASH_ENV
        source $BASH_ENV

     - checkout

     - run: |
        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
        docker build -t gitopsworkshop/my-app:$IMAGE_TAG .

     - run: docker build -t gitopsworkshop/my-app:$IMAGE_TAG .

     - run: docker push gitopsworkshop/my-app:$IMAGE_TAG

     - run: |
        curl -o ./argocd -L https://github.com/argoproj/argo-cd/releases/download/v1.3.0-rc4/argocd-linux-amd64 && chmod +x ./argocd
        if [[ ! -z $PR_NUM ]]; then
            ./argocd app create preview-$PR_NUM \
                --project demo \
                --repo https://github.com/gitops-workshop/my-app-deployment \
                --path . \
                --dest-server https://kubernetes.default.svc \
                --dest-namespace workshop \
                --nameprefix preview-$PR_NUM \
                --sync-policy automated
            curl -H "Authorization: token $GITHUB_TOKEN" -XPOST -d "{\"event\": \"COMMENT\",  \"body\": \"Preview Application URL: https://$ARGOCD_SERVER/applications/preview-$PR_NUM\"}" \
                https://api.github.com/repos/gitops-workshop/my-app/pulls/$PR_NUM/reviews
        else
            ./argocd app delete preview-$PR_NUM || true
        fi
